### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#10]
See screenshot: https://www.dropbox.com/s/reeg30802a5fo1v/Screenshot%202015-07-23%2009.11.42.png?dl=0

**Comment by edwbaker** [comment]
Nothing to worry about really, but nothing we can do about it anyway as NB doesn't support security certificates: http://nationbuilder.com/dtrimble/support_for_ssl_certificates
