### ISSUE TITLE
Check site for missing icons - and replace

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#12]
Missing images/icons on:
- [ ] http://www.opencon2015.org/sponsor
- [ ] http://www.opencon2015.org/program
- [] http://www.opencon2015.org/about_us

**Comment by edwbaker** [comment]
Only the coffee icon was missing on /sponsor, tote never had one.
What images are missing on the other pages?

**Comment by JosephMcArthur** [comment]
When we first moved the site they all went as far as I could see (as did a
image on program which I planned to fix). If that's resolved now then we're
all good.

Joe

On 24 July 2015 at 15:12, Ed Baker notifications@github.com wrote:

> Only the coffee icon was missing on /sponsor, tote never had one.
> What images are missing on the other pages?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RightToResearch/NationBuilder-Theme/issues/12#issuecomment-124536170
> .

## 

Joseph McArthur
Assistant Director: Right to Research Coalition
http://righttoresearch.org/
Co-Lead/Founder: Open Access Button http://openaccessbutton.org/
Twitter: @Mcarthur_Joe
Skype: joseph_mcarthur
Linkedin: http://linkd.in/1BgZ1jU
