### ISSUE TITLE
/attend_mcmaster not redirecting

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#17]
Despite many attempts "http://www.opencon2015.org/attend/mcmaster" won't direct to "http://www.opencon2015.org/attend_mcmaster". http://righttoresearch.nationbuilder.com/attend_mcmaster and http://www.opencon2015.org/attend_mcmaster work, although http://www.opencon2015.org/attend_mcmaster has other errors for some reason (see sidebar).  

Tried deleting redirect, publishing and unpublishing page, setting the theme to default.

**Comment by JosephMcArthur** [comment]
www.opencon2015.org/Satellite/Plan is also having this issue

**Comment by edwbaker** [comment]
Seem to be working now. Probably issues while DNS was propagating.
