### ISSUE TITLE
/community_discussion formats in one column 

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#20]
http://www.opencon2015.org/community_discussion - on my screen it all comes up in a column.

**Comment by JosephMcArthur** [comment]
http://www.opencon2015.org/community_webcasts has a similar issue. Does NB not like having several things embedded on one line or is it a simple case of the page width having changed?

**Comment by edwbaker** [comment]
It depends on the size of the screen whether things are side-by-side or in a single column.

**Comment by JosephMcArthur** [comment]
Really? I have a 23 inch screen and it's displaying in one column. I did
test for that. Am I missing something?

On 11 September 2015 at 14:44, Ed Baker notifications@github.com wrote:

> It depends on the size of the screen whether things are side-by-side or in
> a single column.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RightToResearch/NationBuilder-Theme/issues/20#issuecomment-139550407
> .

## 

Joseph McArthur
Assistant Director: Right to Research Coalition
http://righttoresearch.org/
Co-Lead/Founder: Open Access Button http://openaccessbutton.org/
Twitter: @Mcarthur_Joe
Skype: joseph_mcarthur
Linkedin: http://linkd.in/1BgZ1jU

**Comment by JosephMcArthur** [comment]
Fixed on webcasts (on a draft page being released soon), should be good now!
