### ISSUE TITLE
Need to make Nationbuilder HTML mailtemplate

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#29]

**Comment by JosephMcArthur** [comment]
@edwbaker see email sent on this.

**Comment by JosephMcArthur** [comment]
- [ ] Add logo at top of message: http://d3n8a8pro7vhmx.cloudfront.net/themes/574d634f79bffaed8f000006/attachments/original/1464689629/OpenCon2016_Logo_Horizontal.png?1464689629
- [ ] change font to open sans or something closer to Gotham

**Comment by JosephMcArthur** [comment]
The logo might be far to big...

**Comment by edwbaker** [comment]
I've made the header smaller - the fonts needed to include the stylesheet from Google Fonts in the HTML head, which I've added (they may not load in all email clients - but there is nothing that can be done about that).
