### ISSUE TITLE
Create a resource page template similar to this

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#37]
https://www.google.com/events/rework/videos/

Wouldn't be 100% the same, I think we'd replace the top video with text. We may also use a little more text in the descriptions. 

@edwbaker can you suggest a code template which would do this well? I'm assume a 4X4 grid would do well?

**Comment by edwbaker** [comment]
It would just be a 2x grid, but yes, that would be the way forward

**Comment by JosephMcArthur** [comment]
Okay, I've stuck

.grid-2 {
  float:left;
  width:50%;
  display:table-cell;
}

into the scss template, which should then work right?
