### ISSUE TITLE
Shift domain to OpenCon 2016.org

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#40]
- [x] Will we be able to forward 2015 links? Worried about link breaking. 
- [x] Do the OpenCon2014 links redirect? They don't appear too

**Comment by edwbaker** [comment]
The links redirect - although some of the pages have either been removed or moved to a different URL.

**Comment by edwbaker** [comment]
Change for 2016 made - need to wait 48 hours before moving.
