### ISSUE TITLE
Header resize on scroll

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#49]

**Comment by JosephMcArthur** [comment]
I think this as caused an issue where it sits over the slider which isn't good

**Comment by edwbaker** [comment]
The basic functionality is now all there - what exactly do you want to happen to the logo, site name and menus as you scroll?

**Comment by JosephMcArthur** [comment]
Okay, let's turn this off until it's a bit more polished. Ideally the logo
and site name would increase size. We'd probably want to centre
(vertically) the text too.

Joe

On 16 April 2016 at 11:16, Ed Baker notifications@github.com wrote:

> Assigned #49
> https://github.com/RightToResearch/OpenCon-Website/issues/49 to
> @JosephMcArthur https://github.com/JosephMcArthur.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/RightToResearch/OpenCon-Website/issues/49#event-630018733

## 

Joseph McArthur
Assistant Director: Right to Research Coalition
http://righttoresearch.org/
Co-Lead/Founder: Open Access Button http://openaccessbutton.org/
Twitter: @Mcarthur_Joe https://twitter.com/Mcarthur_Joe
Skype: joseph_mcarthur
Linkedin http://linkd.in/1BgZ1jU

**Comment by JosephMcArthur** [comment]
Definately off for now, it's leaving weird gaps on all the pages.

**Comment by JosephMcArthur** [comment]
Bug: On mobile new header isn't visible when expanded
