### ISSUE TITLE
Add in this plugin for event pages to allow for calendar adds

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#51]
Follow this guide :) https://github.com/ianpatrickhines/add-this-nationbuilder-event

**Comment by edwbaker** [comment]
As you use custom templates for each event the code needs to be added manually to each one. I can run through and do this - but is it in the right place? http://www.opencon2016.org/april_community_call

**Comment by JosephMcArthur** [comment]
Can we put it in the sidebar under "when". I don't need this retrospectively, only for events going forwards. Is it still going to be a manual process for each event?

**Comment by edwbaker** [comment]
Done - will show on all events there (including past ones, but can probably remove it from them if needed.

**Comment by JosephMcArthur** [comment]
Fab! Any other ideas you have to make these pages better are very very much
appreciated.

On 17 April 2016 at 13:14, Ed Baker notifications@github.com wrote:

> Done - will show on all events there (including past ones, but can
> probably remove it from them if needed.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/RightToResearch/OpenCon-Website/issues/51#issuecomment-211106808

## 

Joseph McArthur
Assistant Director: Right to Research Coalition
http://righttoresearch.org/
Co-Lead/Founder: Open Access Button http://openaccessbutton.org/
Twitter: @Mcarthur_Joe https://twitter.com/Mcarthur_Joe
Skype: joseph_mcarthur
Linkedin http://linkd.in/1BgZ1jU

**Comment by JosephMcArthur** [comment]
Can we remove the "add to calendar button" from under the RSVP button on event page. Also, is there any way to attach or link to the calendar invite to an email?
