### ISSUE TITLE
Can we get ORCID's into the NB sign up? 

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#55]

**Comment by edwbaker** [comment]
You'll need to contact NB: 

> How to access custom fields
> 
> If you would like to use custom fields in your nation and are comfortable accepting the complexity of the feature:
> 1. Contact Frontline Customer Support by emailing help@nationbuilder.com to request that custom fields be turned on in your nation. In your email, please include your nation slug and let Frontline know that you have read the When to use custom fields HOWTO (i.e. this page).
> 2. Decide which fields to create as custom people fields and which fields to create as custom donation fields.
> 3. Create the custom fields in the Settings section of your nation.

**Comment by JosephMcArthur** [comment]
Ah okay, this is easy!
