### ISSUE TITLE
Domain Issues

### ISSUE THREAD

**Issue by JosephMcArthur** [RightToResearch/OpenCon-Website#68]
-  [ ] opencon2016.org errors, you need the www. This isn't ideal! 
- [x] There is currently "Single Domain Linux Hosting (USA)” in our 
  whois.com account for opencon2014.org that is set to expire in July. Do we 
  need to worry about this, or ok to just let it expire? 
- [ ] OpenCon2016.org is blocked in Sudan. Can we find out where else it's blocked or do anything about it?

**Comment by edwbaker** [comment]
I've just checked:

1) opencon2016.org redirects to www.opencon2016.org for all pages. What errors are you getting?
2) let it expire
3) Not really. I would guess they might be blocking NationBuilder as it's a political platform?

**Comment by JosephMcArthur** [comment]
1) I've just had people mention they're still having trouble. Very odd. The old links struggle to redirect too, for example old messages on 2014 don't seem to work now which is suprising. 
3) I seem to be able to access other NB sites from there (e.g development.r2rc.org). It's fine if they use a VPN though. It's just mega annoying.

**Comment by JosephMcArthur** [comment]
1) e.g when you type in opencon2016.org/updates into a window it won't go to the site. Is this normal.

**Comment by JosephMcArthur** [comment]
1) e.g a link I just put into a page http://opencon2016.org/sharing_resources doesn't work

**Comment by edwbaker** [comment]
That domain points to the IP I just sent you on chat - do you know what that server is/was? Better to use www.opencon2016.org in all links as that's the actual domain of the site and will be slightly quicker (not using www requires an extra redirect).

**Comment by edwbaker** [comment]
The server has been setup to redirect opencon2016.org to www.opencon2016.org. Might take a little while for DNS to propagate.

There's really not much we can do about blocking by third parties.
